### PR TITLE
IDGEN-111: Support openmrs platform 2.3.x

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/IDGEN-111

### CODE REVIEW

**Comment by ODORA0** [comment]
I don't get why Travis would fail here because I have a build success locally @dkayiwa @mozzy11 
You can checkout this [pastebin](https://pastebin.com/ftrJsRHT)

**Comment by mozzy11** [comment]
@ODORA0  did you take a look at this?? https://talk.openmrs.org/t/no-more-oraclejdk/23173

**Comment by ODORA0** [comment]
Oh yes thankyou @mozzy11, I am a-little confused where the travis.yml file is located

**Comment by dkayiwa** [comment]
@ODORA0 did you even try to look for it in this repository?

**Comment by ODORA0** [comment]
I actually found it in my root directory, which means I have to make a push for the change to openjdk from the oraclejdk I found

**Comment by dkayiwa** [comment]
@ODORA0 can you do the same for the appframework module?

**Comment by ODORA0** [comment]
Sure, coming right up @dkayiwa

**Pull request merged**
