### PR TITLE
WIP- Added Resource Handler Classes and Tests

### PR DESCRIPTION
**Pull request by tendomart**
https://issues.openmrs.org/browse/IDGEN-42

@samuelmale  can you take a look at the chages here and determine which one you want to continue with
cc @dkayiwa

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can we include the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Did you get a chance to look at the travis failure?

**Comment by tendomart** [comment]
Looking into that.We are working in the Travis errors.

**Comment by samuelmale** [comment]
@tendomart can you close this PR?

**Comment by tendomart** [comment]
@samuel34 but you did not indicate to me which path you are taking !!

**Pull request closed without merging**
