### PR TITLE
TRUNK-4610: replace deprecated TimerFactoryBean with Spring's suggested ...

### PR DESCRIPTION
**Pull request by kristopherschmidt**
...scheduling.concurrent

Tested that the task fires off successfully in the embedded jetty container, running both openmrs-core Spring 3 (master) and Spring 4 (spring-4 branch). There is also an integration test for the task runner (AuthenticatedTaskIT) which passes.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kristopherschmidt was this a mere improvement? Or one of those things required by spring 4? :)

**Comment by kristopherschmidt** [comment]
This is a requirement for Spring 4. TimerFactoryBean has been removed from
Spring 4, so the ID Generation module throws class not found errors when
loaded. A number of other modules rely on ID Generation.

It theoretically would have been possible to just add the source code of
TimerFactoryBean to core, just like I added SimpleFormController back. But
in this case, the only module I have run across so far that uses
TimerFactoryBean is ID Generation, so I figured it was better to just fix
it to the desired approach rather than add in more hacks.

**Comment by dkayiwa** [comment]
@kristopherschmidt with these changes, will this module run fine in lower versions of openmrs (before spring4) ?

**Comment by kristopherschmidt** [comment]
Yes. idgen is still built against openmrsversion 1.6.5 which is using
Spring dependency 2.5.6. It builds and run tests fine, the integration test
AuthenticatedTaskIT passes, and I also tested openmrs-core/master on Jetty.

**Comment by dkayiwa** [comment]
@kristopherschmidt does this mean that the new replacement class already existed in Spring 2.5.6?

**Comment by kristopherschmidt** [comment]
Yes, both of them are in spring-2.5.6.jar.

**Pull request merged**
