### PR TITLE
IDGEN-43: create german messages.properties

### PR DESCRIPTION
**Pull request by STheis**
german translation of id gen module

### CODE REVIEW

**Comment by djazayeri** [comment]
@STheis I discovered while committing your other translations that it's also necessary to add an element mentioning messages_de in omod/src/main/resources/config.xml

Can you add that change to this PR also (and make this change in others going forwards)?

**Comment by STheis** [comment]
Yes, I make it.

**Comment by djazayeri** [comment]
Like I commented on the other module, can you squash these commits?

**Comment by STheis** [comment]
Merged them in PR #15

**Pull request closed without merging**
