### PR TITLE
IDGEN-101 Link 'My Account' in navbar to user's account page

### PR DESCRIPTION
**Pull request by cnagadya**
## JIRA TICKET NAME:

[IDGEN-101 Link Log Entries EndPoints to OWA](https://issues.openmrs.org/browse/IDGEN-101)

## SUMMARY:
Link 'My Account' in navbar to user's account page

### CODE REVIEW

**Comment by adamsdenniskariuki** [comment]
@cnagadya Remove the space from line 87

**Comment by cnagadya** [comment]
Thanks for the review @adamsdenniskariuki. Removed it, plus the unnecessary comments

**Comment by Farhanisto** [comment]
Looks good

**Comment by Ewanjiru** [comment]
looks good

**Pull request merged**
