### PR TITLE
Change invalid default values for datetime field

### PR DESCRIPTION
**Pull request by dave91x**
Two of the datetime fields in the sql had invalid default values assigned, which caused this module to fail every time I tried to add it to my OpenMRS build.  I made this change in my local module and after that, OpenMRS was able to load and run it.  This was critical in that other modules, like the coreapp module depended on the idgen module, so without this working, the rest of it was a mess.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@dave91x thanks for the contribution! :)
Does your runtime properties file connection string have this? &zeroDateTimeBehavior=convertToNull

You would also need to first created a ticket as advised at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dave91x** [comment]
Here is my connection string in the openmrs-runtime.properties file as auto-generated by the OpenMRS initialization wizard:

connection.url=jdbc\:mysql\://localhost\:3306/openmrs?autoReconnect\=true&sessionVariables\=default_storage_engine\=InnoDB&useUnicode\=true&characterEncoding\=UTF-8

The parameter you mentioned is not there.

**Comment by dkayiwa** [comment]
Can you add it and test if all is well?

**Comment by dkayiwa** [comment]
By the way are you following this? https://talk.openmrs.org/t/modules-of-ref-app-2-4-uiframeworkexception-no-controller-provider-coreapps/8180/18

**Comment by dkayiwa** [comment]
We decided to go with this: https://github.com/openmrs/openmrs-module-idgen/commit/e7c1648a11bd0519aebec9b4b1fe6b5053ae136e

**Pull request closed without merging**
